name: Gradle Package

on: [push, pull_request]

jobs:
  publish:
    if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          allow-snapshots: true

      - name: test with Gradle
        run: gradle -q publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
  test:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          allow-snapshots: true

      - name: test with Gradle
        if: ${{ github.event_name == 'pull_request' }}
        run: gradle -q test
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
